version: 0.2

phases:
  pre_build:
    commands:
      # Docker Hub へのログイン
      - echo Logging in to Docker Hub...
      - echo $DOCKER_HUB_PASSWORD | docker login -u $DOCKER_HUB_USERNAME --password-stdin
      
      # 環境変数設定
      - AWS_ACCOUNT_ID=$(aws sts get-caller-identity --query 'Account' --output text)
      - ECR_URL=${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com
      - URI=${ECR_URL}/${IMAGE_NAME}

      # AWS ECR へのログイン
      - echo Logging in to AWS ECR...
      - aws ecr get-login-password --region ap-northeast-1 | docker login --username AWS --password-stdin ${ECR_URL}
  build:
    commands:
      - docker build -t $URI:latest -t $URI:$CODEBUILD_RESOLVED_SOURCE_VERSION .
      - docker push $URI:latest
      - docker push $URI:$CODEBUILD_RESOLVED_SOURCE_VERSION
      - printf '{"Version":"1.0","ImageURI":"%s"}' $URI:latest > imageDetail.json
artifacts:
  files: 
    - imageDetail.json
    - appspec.yml
    - taskdef.json